### ISSUE TITLE
`RnsSDK is not a constructor` error when running example

### ISSUE THREAD

**Issue by dcts** [radixnameservice/sdk#52]
I tried running the "domain status" example from the docs ([reference](https://docs.rns.foundation/#/developers/v1.0.x/domain-status)), but get this error:

```bash
   const rns = new RnsSDK({
               ^

TypeError: RnsSDK is not a constructor
    at statusExample (file:///Users/dcts/code/index.js:43:16)
    at file:///Users/dcts/code/index.js:49:1
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.9.0
```

When I console log the import I get this:

```js
import RnsSDK from '@radixnameservice/rns-sdk';
console.log(RnsSDK);
// => { default: [Getter] }

```

**Comment by dcts** [comment]
For me this fixed the issue:

```js
const rns = new RnsSDK.default({
    network: 'mainnet' // or mainnet
});
```

**Comment by jameswylie** [comment]
Quick Q:

Do you primarily use CommonJS modules or ES modules within your project ATM?

**Comment by dcts** [comment]
> Do you primarily use CommonJS modules or ES modules within your project ATM?

I am indifferent. Default for me is commonjs (when initializing a project with `npm init -y`) but switching to modules is just adding 1 line to package json so it really doesnt matter that much 😃

**Comment by jameswylie** [comment]
Cool cool! In terms of this specific project, are you utilising CommonJS?

In order to narrow down the specific config that we need to provide coverage on, could you let us know if the following works for you?

import * as RnsSDK from '@radixnameservice/rns-sdk';

Cheers!

**Comment by dcts** [comment]
Unfortunately this does not solve this issue for me, see log:

```js
import RnsSDK from '@radixnameservice/rns-sdk';
console.log(RnsSDK);  // => { default: [Getter] }
```

```js
import * as RnsSDK from '@radixnameservice/rns-sdk';
console.log(RnsSDK);  // => [Module: null prototype] { default: { default: [Getter] } }
```

### Only this worked for me:

```js
// This is my preferred solution
import RnsSDKImport from '@radixnameservice/rns-sdk';
const RnsSDK = RnsSDKImport.default;
console.log(RnsSDK);  // => [class RnsSDK]
``` 

```js
// This also works but its ugly and not readable, I'm sure you don't want to do this,
// but sharing in case relevant
const RnsSDK = (await import('@radixnameservice/rns-sdk')).default.default;
console.log(RnsSDK);  // => [class RnsSDK]
```

**Comment by dcts** [comment]
If you'd like to play around with the setup and repository yourself, I am using the SDK in this project:
https://github.com/dcts/xrd-domain-hunt/

**Comment by jameswylie** [comment]
Hey man, this is now fixed in v3.2.1 (almost a year later haha!) 👍
